# -*- coding: utf-8 -*-
"""Diabetes_sistemcerdas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4z2nDi5583u9y2t9ArhXnRas6pwaUa-

Nama/NIM
Marah nafiah M./ E42240962
Adzra Syafa K./E42241974
Savana Farel A/E42240035
Devina Putri I./E422440721
Dewi Suciyo W./E42240571
"""

import numpy as np

import matplotlib.pyplot as plt

import pandas as pd

import seaborn as sns

from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv("/content/diabetes.csv")
df

df.info()

df.info()

df['Outcome'].value_counts()

correlation = df.corr()

correlation['Outcome'].sort_values(ascending=False)

correlation = df.corr()

correlation['Outcome'].sort_values(ascending=False)

plt.figure(figsize=(10,8))

plt.title('Correlation of Attributes with Class variable')

a = sns.heatmap(correlation, square=True, annot=True, fmt='.2f', linecolor='white')

a.set_xticklabels(a.get_xticklabels(), rotation=90)

a.set_yticklabels(a.get_yticklabels(), rotation=30)

plt.show()

X = df.drop(['Outcome'], axis=1)

y = df['Outcome']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X),columns=X.columns)

X

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.254321, random_state = 0)

X_train.shape, X_test.shape

X_train

X_test

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5,weights='distance',metric='euclidean')

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

y_pred

from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

y_pred_train = knn.predict(X_train)

print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

print('Training set score: {:.4f}'.format(knn.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(knn.score(X_test, y_test)))

y_test.value_counts()

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Negatives(TP) = ', cm[0,0])

print('\nTrue Positives(TN) = ', cm[1,1])

print('\nFalse Negatives(FP) = ', cm[0,1])

print('\nFalse Positives(FN) = ', cm[1,0])

plt.figure(figsize=(6,4))

cm_matrix = pd.DataFrame(cm, columns=['Actual Benign:2', 'Actual Malignant:4'], index=['Predict Benign:2', 'Predict Malignant:4'])

sns.heatmap(cm_matrix, annot=True, fmt='d', cmap='YlGnBu')

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))